# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b42717c19e96de7718f0126953bf31685a4adf0dd14e11e8084a63d2af83d36d92a187cf28eb551dc559c4fd226e120ef56f2371b90610f2f2f897296d05356

test:
  secret_key_base: ffac1a6488954486f55dcc02406c355f1e1e6c7e8a4cb38e837731fc3af2dd6c4ada29d1582b100c3fc4b070936820ae83af1d31f510a2ea1adba85dd7331586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
